//! Backtest types and data structures.

use ferrum_core::types::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Configuration for a backtest run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestConfig {
    /// Trading pair to backtest.
    pub pair: TradingPair,
    /// Exchange connector to simulate.
    pub connector: String,
    /// Start time (unix ms).
    pub start_time: i64,
    /// End time (unix ms).
    pub end_time: i64,
    /// Candle interval.
    pub interval: Interval,
    /// Initial balance.
    pub initial_balance: f64,
    /// Quote asset (e.g. "USDT").
    pub quote_asset: String,
    /// Trading fee (0.001 = 0.1%).
    pub fee_rate: f64,
    /// Slippage model (percentage).
    pub slippage: f64,
    /// Leverage.
    pub leverage: f64,
}

impl Default for BacktestConfig {
    fn default() -> Self {
        Self {
            pair: TradingPair::new("BTC", "USDT"),
            connector: "binance".to_string(),
            start_time: 0,
            end_time: 0,
            interval: Interval::H1,
            initial_balance: 10000.0,
            quote_asset: "USDT".to_string(),
            fee_rate: 0.001,
            slippage: 0.0005,
            leverage: 1.0,
        }
    }
}

/// A trade executed during backtesting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestTrade {
    pub id: String,
    pub pair: TradingPair,
    pub side: Side,
    pub entry_price: f64,
    pub exit_price: Option<f64>,
    pub amount: f64,
    /// PnL for this trade (realized).
    pub pnl: f64,
    /// Fee paid for entry.
    pub entry_fee: f64,
    /// Fee paid for exit.
    pub exit_fee: f64,
    /// Entry timestamp.
    pub entry_time: i64,
    /// Exit timestamp.
    pub exit_time: Option<i64>,
    /// Is position still open?
    pub is_open: bool,
}

/// Backtest result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestResult {
    pub config: BacktestConfig,
    pub trades: Vec<BacktestTrade>,
    pub metrics: crate::metrics::BacktestMetrics,
    /// Final portfolio value.
    pub final_value: f64,
    /// Equity curve: (timestamp, portfolio_value) pairs.
    pub equity_curve: Vec<(i64, f64)>,
    /// Orders placed.
    pub orders_placed: usize,
    /// Candles processed.
    pub candles_processed: usize,
}

/// Signal generated by a backtest strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TradeSignal {
    Buy,
    Sell,
    Hold,
    ClosePosition,
}

/// Market data available at a point in time during backtesting.
#[derive(Debug, Clone)]
pub struct MarketContext {
    pub current_candle: Candle,
    pub historical_candles: Vec<Candle>,
    pub balance: f64,
    pub position: Option<BacktestTrade>,
    pub indicators: HashMap<String, f64>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backtest_config_default() {
        let config = BacktestConfig::default();
        assert_eq!(config.initial_balance, 10000.0);
        assert_eq!(config.fee_rate, 0.001);
    }
}
